name: study_tracker_p10
description: 'Starter P10 — offline-first: SQLite lokal, sinkronisasi dua arah, conflict resolution (last-write-wins).'
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.3
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
